# Generated by Django 5.1.4 on 2026-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocache',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audiocache',
            name='audio_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
