# Generated by Django 5.1.4 on 2026-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_audiocache_transcript_alter_audiocache_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_template',
            field=models.CharField(choices=[('sales_counter', 'Sales counter'), ('fitness_counter', 'Fitness counter'), ('github_checklist', 'GitHub checklist'), ('study_checklist', 'Study checklist'), ('reflection_manual', 'Reflection manual'), ('generic', 'Generic')], default='generic', max_length=30),
        ),
    ]
