# Generated by Django 5.1.4 on 2026-09-28 20:35

from pgvector.django import VectorExtension
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_goal_template'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='goal',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
