# Generated by Django 5.1.4 on 2026-09-25 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_hash', models.CharField(max_length=64, unique=True)),
                ('audio_url', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('counter', 'Counter'), ('checklist', 'Checklist'), ('manual', 'Manual')], max_length=20)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed')], db_index=True, default='active', max_length=20)),
                ('result_value', models.IntegerField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parse_result', models.JSONField(blank=True, default=dict)),
                ('verdict', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='goals_goal_user_id_7ad9fc_idx'), models.Index(fields=['user_id', 'deadline'], name='goals_goal_user_id_38b5f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_message', models.TextField()),
                ('user_response', models.TextField(blank=True, default='')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='goals.goal')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='goals.goal')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('value', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='goals.goal')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['goal', 'logged_at'], name='goals_progr_goal_id_b4c574_idx')],
            },
        ),
    ]
