# Generated by Django 5.1.4 on 2026-09-27 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('streak', models.IntegerField(default=0)),
                ('total_goals', models.IntegerField(default=0)),
                ('completed_goals', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google-cal', 'Google Calendar'), ('slack', 'Slack'), ('notion', 'Notion')], max_length=20)),
                ('access_token', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'provider'], name='accounts_in_user_id_5ad556_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'provider'), name='uniq_integration_user_provider')],
            },
        ),
    ]
